# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Filter-Sort
version:      1.01
version_from: lib/XML/Filter/Sort.pm
installdirs:  site
requires:
    Test::Simple:                  0.41
    XML::SAX:                      
    XML::SAX::Writer:              

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
